[default.extend-words]

[files]
extend-exclude = [
    "target/",
    "**/*.rlib",
    "**/*.o",
    "**/*.d",
    "**/*.rmeta",
    "CHANGELOG.md",
    "chat_server/fixtures/*",
    "chat_core/fixtures/*",
    "notify_server/*.html",
]
