### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "YP",
    "email": "yp51@acme.org",
    "password": "12345678"
}

### signin user (valid)
# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "yp51@acme.org",
    "password": "12345678"
}

@token = {{signin.response.body.token}}

### signin user (invalid)
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "yp51@acme.org",
    "password": "wrongpassword"
}



### get chat list
GET http://localhost:6688/api/chat
Authorization: Bearer {{token}}
