### signup user1

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "YP",
    "email": "yp51@acme.org",
    "password": "12345678"
}

### signup user2
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "YP1",
    "email": "yp511@acme.org",
    "password": "12345678"
}

### signin user (valid)
# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "yp51@acme.org",
    "password": "12345678"
}

@token = {{signin.response.body.token}}

### signin user (invalid)
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "yp51@acme.org",
    "password": "wrongpassword"
}

### create chat
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "acme",
    "members": [1, 2],
    "public": false
}

### get chat list
GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}

### get user list
GET http://localhost:6688/api/users
Authorization: Bearer {{token}}
